FROM golang:1.19-alpine
ENV SONNEN__BASEURL=http://localhost
ENV CHARGEHQ__APIKEY=your_api_key
ENV CHARGEHQ__REFRESHMS=120000
WORKDIR /app

# pre-copy/cache go.mod for pre-downloading dependencies and only redownloading them in subsequent builds if they change
COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY *.go ./
RUN go build -v -o /service

CMD ["/service"]